version: '3.3'
volumes:
  couch-data:
services:
  couchdb:
    image: isl-dsdc.ca.com:5000/analytics/lddscouchdb:$buildnumber
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
      - "5986:5986"
    environment:
      - IPADDRESS=SLAVENODE1_IPADDRESS
      - COUCHDB_COOKIE=sunday
      - COUCHDB_USER=lddsuser
      - COUCHDB_PASSWORD=interOP@123
      - COUCHDB_SECRET=monday
      - COUCHDB_SYNC_ADMINS_NODE=MASTER_IPADDRESS
      - COUCHDB_SYNC_ADMINS_NODENAME=MASTER_IPADDRESS
      - COUCHDB_ADMINPORT=SLAVENODE1_COUCHDBPORT
    volumes:
      - couch-data:/opt/couchdb/data/
